services:
  # frontend:
  #   build: ./FE
  #   container_name: FE
  #   expose:
  #     - "8081"
  #   volumes:
  #     - ./FE:/FE
  #     - /FE/node_modules
  #   networks:
  #     - app_network
  #   restart: always
  #   environment:
  #     - TZ=Asia/Seoul

  backend:
    build: ./BE/undaid
    container_name: BE
    expose:
      - "8080"
    depends_on:
      mysql:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/boney?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      TZ: Asia/Seoul
      JAVA_SECURITY_PROPERTIES:
        jdk.internal.reflect.permitAll=true
        jdk.reflect.allowNativeAccess=true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - app_network
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
  mysql:
    build: 
      context: ./mysql
    container_name: mysql
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
      MYSQL_INIT_COMMAND: "SET GLOBAL host_cache_size=0"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/pid:/pid
    networks:
      - app_network
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  mysql_data:
  mysql_pid:

networks:
  app_network:
    external: true
