services:
  mysql_test:
    build: 
      context: ./mysql
    container_name: mysql_test
    expose:
      - "3306"
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
      MYSQL_INIT_COMMAND: "SET GLOBAL host_cache_size=0"
    volumes:
      - type: tmpfs
        target: /var/lib/mysql  # 메모리에서만 동작, 재시작 시 데이터 없어짐
    networks:
      - app_network
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  app_network:
    external: true