server:
  port: 8080

spring:
  application:
    name: boney

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boney?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update  # none, update, create, create-drop
    properties:
      hibernate:
        show_sql: true  # SQL ?? ??
        format_sql: true  # SQL ?? ???
        use_sql_comments: true  # SQL ?? ?? ??
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: "55aa1cfe5d36d1a257676005273b51d0"
            client-secret: "7kcpWFae1kVCxCyWc5dOS89XE0y0plOw"
            redirect-uri: "http://localhost:8080/api/v1/auth/login/kakao/callback"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: kakao
            scope:
              - account_email
#              - profile_nickname
#              - profile_image
#              - name
#              - gender
#              - age_range
#              - birthday
#              - birthyear
#              - phone_number

jwt:
  secret: "HFwodSBtld8oN1DAfp1ngP6NAwvQkHYCbLpaA79yPKo="